#!/bin/bash
#
# ror
#
# chkconfig: 2345 96 82
# description: ror

start() {
    /usr/local/cpanel/bin/rormgr --startboot
}

stop() {
    /usr/local/cpanel/bin/rormgr --stopall
}

status() {
    /usr/local/cpanel/bin/rormgr --statusall
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
esac
